name: retrofit_generator_example
description: An example project for the retrofit_generator package.
version: 1.0.0
environment:
  sdk: ">=3.8.0 <4.0.0"

publish_to: none

dependencies:
  retrofit:
    git:
      url: https://github.com/Flutter-Fox/retrofit.dart.git
      ref: downgrade/analyzer
      path: retrofit
  dio: ^5.8.0

dev_dependencies:
  build_runner: ^2.4.10
  retrofit_generator:
    path: ../../generator
